"""Artifact storage protocol."""

from __future__ import annotations

from typing import Protocol

import numpy as np

from ml.lib.types import DinoArtifacts, SegmentationResult


class ArtifactStore(Protocol):
    def save_image(self, image_id: str, rgb: np.ndarray, raw_bytes: bytes) -> None: ...

    def load_rgb(self, image_id: str) -> np.ndarray: ...

    def image_exists(self, image_id: str) -> bool: ...

    def save_dino(self, image_id: str, artifacts: DinoArtifacts) -> None: ...

    def save_segmentation(self, image_id: str, result: SegmentationResult) -> None: ...

    def load_dino(self, image_id: str) -> DinoArtifacts: ...

    def segmentation_ready(self, image_id: str) -> bool: ...

    def get_mask_bytes(self, image_id: str) -> bytes: ...

    def get_mask_metadata(self, image_id: str) -> dict: ...

    def cleanup_temp(self, image_id: str) -> None: ...
